### ISSUE TITLE
How To Implement The Full End-To-End Pipeline?

### ISSUE THREAD

**Issue by josephius** [SketchyScene/SketchySceneColorization#6]
It seems from an initial look through of the various readme files that the pipeline also requires the segment_data_generation.py script from the SketchyScene repository to perform an initial preprocessing step on the sketches.  Currently this means that both repositories need to be utilized...  Are there any plans to integrate this into the SketchySceneColorization repository in the future?

Also, it appears that the Foreground Instance Colorization module is designed to handle individual instances for inference rather than being able to take the output of the Instance Matching module.  This seems to be missing a step where the instances matched are separated and individually put through the Foreground Instance Colorization module.  Are there any plans to add this functionality?

Finally, the Background Colorization module seems to be lacking an inference method.  While it should be possible to utilize the test method for the same purpose, are there plans to implement an inference method to handle example data?

**Comment by MarkMoHR** [comment]
Hi @josephius ,
Thanks for your interest on our project.

Regarding the first issue, as described in the paper, the Mask R-CNN model is used as a plug-and-play module, because the segmentation process should only be done once to obtain the instance segmentation results. So we recommend users to perform an initial preprocessing step on the sketches first and then reuse the segmented data in the matching step.

Regarding the second and third issue, we will provide the inference code of the whole pipeline, which means users can perform the language-based colorization process as the results shiown in the paper. However, the authors are tooooo busy these days to organize the code :-( ... But we promise to do so before the of begining of SIGA'19 conference.

Regarding the future plans, we might design a demo website which makes it easier for users to use our system. But we are not sure. This depends on time and many other things : )
